heat_template_version: 2014-10-16
parameters:
  file:
    type: string
    default: {get_file: test_script.sh}
resources:
  random:
    type: OS::Nova::Server 
    properties:
      flavor: m1.small
      image: fedora-21-atomic-5
